### ISSUE TITLE
Meilleure présentation 

### ISSUE THREAD

**Issue by Asmitta-01** [Skrt-Time/Skrt-ChatBot#1]
Le code n'est pas propre. Faut plus de commentaires et de clarté dans les noms de variables, entre autres.
🦦🦦

**Comment by Asmitta-01** [comment]
**### Eh eh**


Je ferme

**Comment by Skrt-Time** [comment]
Tu fermes quoi


Sent from Yahoo Mail for iPhone


On Thursday, August 17, 2023, 9:12 PM, Brayan Tiwa ***@***.***> wrote:




### Eh eh

Je ferme
